#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod augustus_registry;
pub mod erc20;
pub mod i_aave_oracle;
pub mod i_flash_loan_recipient;
pub mod i_para_swap_augustus;
pub mod i_para_swap_augustus_registry;
pub mod i_pool;
pub mod i_pool_addresses_provider;
pub mod i_pool_data_provider;
pub mod i_quoter_v2;
pub mod i_vault;
pub mod il2_encoder;
pub mod il2_pool;
pub mod liquidator;
pub mod mock_oracle;
pub mod owned;
pub mod safe_erc20;
